cart/urls.py
from django.conf.urls import url

from cart import views

urlpatterns = [
    # 加入购物车
    url(r'add_cart/', views.add_cart, name='add_cart'),
    # 购物车
    url(r'cart/', views.cart, name='cart'),
    # 结算
    url(r'place_order/', views.place_order, name='place_order'),
    # 刷新价格
    url(r'^f_price/', views.f_price, name='f_price'),
    # 购物车数据
    url(r'^cart_count/', views.cart_count, name='cart_count'),
    # 修改购物车中商品的个数
    url(r'^change_goods_num/', views.change_goods_num, name='change_goods_num'),
]

flask/flask/urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

fresh_shop/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import static

from fresh_shop.settings import MEDIA_ROOT, MEDIA_URL

from goods import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^goods/', include('goods.urls', namespace='goods')),
    url(r'^user/', include('user.urls', namespace='user')),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^order/', include('order.urls', namespace='order')),
    # 配置首页
    url(r'^$', views.index),
]
urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

fresh_shop_back/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import static

from fresh_shop_back.settings import MEDIA_ROOT, MEDIA_URL
from utils.upload_images import upload_image

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^user/', include('user.urls', namespace='user')),
    url(r'^goods/', include('goods.urls', namespace='goods')),
    # 编辑器上传图片
    url(r'^util/upload/(.*)', upload_image)
]

urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

goods/urls.py
from django.conf.urls import url

from goods import views

urlpatterns = [
    # 商品分类
    url(r'^goods_category_list/', views.goods_category_list, name='goods_category_list'),
    # 商品分类编辑
    url(r'^goods_category_detail/(\d+)/', views.goods_category_detail, name='goods_category_detail'),
    # 商品列表
    url(r'^goods_list/', views.goods_list, name='goods_list'),
    # 商品添加
    url(r'^goods_add/', views.goods_add, name='goods_add'),
    # 删除商品
    url(r'^goods_del/(\d+)/', views.goods_del, name='goods_del'),
    # 编辑商品
    url(r'^goods_edit/(\d+)/', views.goods_edit, name='goods_edit'),
    # 商品描述
    url(r'^goods_desc/(\d+)/', views.goods_desc, name='goods_desc'),
]

order/urls.py
from django.conf.urls import url

from order import views

urlpatterns = [
    # 下单
    url(r'^order/', views.order, name='order'),
    # 订单中心
    url('user_order/', views.user_order, name='user_order'),
    # 收货地址
    url('user_order_site/', views.user_order_site, name='user_order_site'),
]

user/urls.py
from django.conf.urls import url

from user import views

urlpatterns = [
    # 登录
    url(r'^login/', views.login, name='login'),

    # 首页
    url(r'^index/', views.index, name='index')
    # 注册
    # url(r'^register/', views.register, name=register)
]

cart/models.py
from django.contrib.auth.models import User
from django.db import models

from goods.models import Goods


class ShoppingCart(models.Model):
    """
    购物车
    """
    user = models.ForeignKey(User, verbose_name='用户', on_delete=models.CASCADE)
    goods = models.ForeignKey(Goods, verbose_name='商品', on_delete=models.CASCADE)
    nums = models.IntegerField(default=0, verbose_name='数量')
    add_time = models.DateTimeField(auto_now_add=True, verbose_name='添加时间')
    is_select = models.BooleanField(default=True)

    class Meta:
        db_table = 'f_shopping_cart'

cart/views.py
from django.shortcuts import render

from django.http import JsonResponse

from goods.models import Goods
from cart.models import ShoppingCart
from user.models import UserAddress


def add_cart(request):
    if request.method == 'POST':
        # 加入到购物车，需判断用户是否登录
        # 如果登录，加入到购物车中的数据，其实就是加入到数据库中购物车表中(设计不好的办法)

        # 如果登录，加入到购物车中的数据，存储到session中（设计相对比较好的）
        # 如果没有登录，则加入到购物车中的数据，是加入到session中
        # session中存储数据: 商品id，商品数量，商品的选择状态
        # 如果登录，则把session中数据同步到数据库中（中间件同步数据）

        # 1. 获取商品id和商品数量
        goods_id = int(request.POST.get('goods_id'))
        goods_num = int(request.POST.get('goods_num'))
        # 2. 组装存到session中的数据格式
        goods_list = [goods_id, goods_num, 1]
        # {'goods':[[1,2,1],[2,5,1],[5,1,1]....]}
        if request.session.get('goods'):
            # 说明session中存储了加入到购物车的商品信息
            # 判断当前加入到购物车中的数据，是否已经存在于session中
            # 如果存在，则修改session中该商品的数量
            # 如果不存在，则新增
            flag = 0
            session_goods = request.session['goods']
            for goods in session_goods:
                # 判断如果加入到购物中数据，已经存在于session中，则修改
                if goods[0] == goods_id:
                    goods[1] = int(goods[1]) + int(goods_num)
                    flag = 1
            if not flag:
                # 如果不存在，则添加
                session_goods.append(goods_list)
            request.session['goods'] = session_goods
            goods_count = len(session_goods)
        else:
            data = []
            data.append(goods_list)
            request.session['goods'] = data
            goods_count = 1
        return JsonResponse({'code': 200, 'msg': '请求成功', 'goods_count': goods_count})


def cart(request):
    if request.method == 'GET':
        # 如果没有登录，则从session中取商品的信息
        # 如果登录，还是从session中取数据(保证数据库中的商品和session中商品一致)
        session_goods = request.session.get('goods')
        if session_goods:
            # 获取session中所有的商品id值
            goods_all = []
            for goods in session_goods:
                cart_goods = Goods.objects.filter(pk=goods[0]).first()
                goods_number = goods[1]
                total_price = goods[1] * cart_goods.shop_price
                goods_all.append([cart_goods, goods_number, total_price])
            # 获取商品对象
            # 前台需要商品信息，商品的个数，商品的总价
            # 后台返回结构[[goods objects, number, total_price],[goods objects, number, total_price]]
        else:
            goods_all = ''
        return render(request, 'cart.html', {'goods_all': goods_all})


def place_order(request):

    if request.method == 'GET':
        # 获取当前登录系统的user_id
        user_id = request.session['user_id']
        # 获取当前勾选的商品用于下单
        cart_goods = ShoppingCart.objects.filter(user_id=user_id, is_select=True)
        # 在购物车对象上绑定一个total_price字段，用于存商品的总价
        for cart in cart_goods:
            cart.total_price = cart.nums * cart.goods.shop_price
        # 获取订单地址
        addresses = UserAddress.objects.filter(user_id=user_id)
        return render(request, 'place_order.html', {'carts': cart_goods, 'addresses': addresses})


def f_price(request):
    """
    返回购物车或session中商品的价格，和总价
    {key:[[id1, price1],[id2, price2]], key2: total_price}
    """
    if request.method == 'GET':
        user_id = request.session.get('user_id')
        if user_id:
            # 获取当前登录系统的用户的购物车中的数据
            carts = ShoppingCart.objects.filter(user_id=user_id)
            cart_data = {}
            cart_data['goods_price'] = [(cart.goods_id,
                                         cart.nums * cart.goods.shop_price)
                                        for cart in carts]
            all_price = 0
            # 总的价格
            for cart in carts:
                if cart.is_select:
                    all_price += cart.nums * cart.goods.shop_price
            cart_data['all_price'] = all_price
        else:
            # 拿到session中所有的商品信息,[id, num, is_select]
            session_goods = request.session.get('goods')
            # 返回数据结构，{’goods_price'：[[id1, price1],[id2, price2]...]}
            cart_data = {}
            data_all = []
            # 计算总价
            all_price = 0
            for goods in session_goods:
                data = []
                data.append(goods[0])
                g = Goods.objects.get(pk=goods[0])
                data.append(int(goods[1]) * g.shop_price)
                # 生成的data为: [id1, price1]
                data_all.append(data)
                # 判断如果商品勾选了，才计算总价格
                if goods[2]:
                    all_price += int(goods[1]) * g.shop_price
            cart_data['goods_price'] = data_all
            cart_data['all_price'] = all_price
        return JsonResponse({'code': 200, 'cart_data': cart_data})


def cart_count(request):
    if request.method == 'GET':
        # 判断购物车中商品的个数
        user_id = request.session.get('user_id')
        # 当前购物车中的商品数量
        if user_id:
            # 如果用户登录。则回去购物车表中的商品个数
            count = ShoppingCart.objects.filter(user_id=user_id).count()
        else:
            # 如果用户没有登录，则回去session中的商品个数
            session_goods = request.session.get('goods')
            count = len(session_goods)
        return JsonResponse({'code': 200, 'msg': '请求成功', 'count': count})


def change_goods_num(request):
    if request.method == 'POST':
        # 修改购物车中商品的个数
        # 1. 先判断用户登录与否，如果用户没有登录，则修改session中商品的个数
        # 2. 如果用户登录，需要判断当前修改的商品是否存在于session中，如果存在，则修改session。如果不存在则修改购物车的表
        # 获取修改的商品id，商品个数，商品选择状态
        goods_id = request.POST.get('goods_id')
        goods_num = int(request.POST.get('goods_num'))
        is_select = int(request.POST.get('is_select'))

        user_id = request.session.get('user_id')

        # 先判断要修改的商品是否存在于session中，如果存在则修改session中的商品个数和选择状态
        session_goods = request.session.get('goods')
        # goods的结构为: [id1, num, is_select]
        if session_goods:
            for goods in session_goods:
                if goods_id == goods[0]:
                    # 修改session中商品的个数和选择状态
                    goods[1] = goods_num
                    goods[2] = is_select
            request.session['goods'] = session_goods

        # 如果用户登录了，则需要在修改购物车中数据，因为session中的商品有可能并不在购物车表中
        if user_id:
            # 修改购物车中商品个数
            ShoppingCart.objects.filter(user_id=user_id, goods_id=goods_id).update(nums=goods_num,
                                                                                   is_select=is_select)
        return JsonResponse({'code': 200, 'msg': '请求成功'})

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}

        {% endblock %}

    </title>


    {% block css %}
    {% endblock %}



    {% block js %}
    {% endblock %}


</head>
<body>

    {# 放顶部菜单栏 #}
    {% block header %}
    {% endblock %}

    {# 放左侧菜单栏 #}
    {% block aside %}
    {% endblock %}



    {% block content %}
    {% endblock %}


</body>
</html>

templates/base_main (2).html
{% extends 'base.html' %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/main.css">
{% endblock %}

{% block js %}
    {% load static %}
    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <script type="text/javascript">
        <!-- 获取用户的登录用户名 -->
        $.get('/user/is_login/', function(data){
            if(data.code == '200'){
                $('.login_info em').html(data.username)
                <!--展示当前用户的信息-->
                $('.login_info').show()
                <!--隐藏登录注册按钮-->
                $('.login_btn').remove()
            }
        })

        <!-- 获取购物车中的商品个数 -->
        $.get('/cart/cart_count/', function(data){
            if(data.code == '200'){
                $('#show_count').html(data.count)
                $('.total_count em').html(data.count)
            }
        })
    </script>
{% endblock %}

{% block header %}
<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
				<div class="login_info fl">
					欢迎您：<em></em>
                    <span>|</span>
                    <a href="{% url 'user:logout' %}">注销</a>
					<span>|</span>
				</div>
				<div class="login_btn fl">
					<a href="{% url 'user:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'user:register' %}">注册</a>
				</div>
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'user:user_center_order' %}">用户中心</a>
					<span>|</span>
					<a href="{% url 'cart:cart' %}">我的购物车</a>
					<span>|</span>
					<a href="{% url 'order:user_order' %}">我的订单</a>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

{% block search %}
    <div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="/static/images/logo.png"></a>
		<div class="search_con fl">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
		<div class="guest_cart fr">
			<a href="{% url 'cart:cart' %}" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">0</div>
		</div>
	</div>
{% endblock %}

{% block footer %}
    <div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
    <script type="text/javascript" src="js/slideshow.js"></script>
	<script type="text/javascript">
		BCSlideshow('focuspic');
		var oFruit = document.getElementById('fruit_more');
		var oShownum = document.getElementById('show_count');

		var hasorder = localStorage.getItem('order_finish');

		if(hasorder)
		{
			oShownum.innerHTML = '2';
		}

		oFruit.onclick = function(){
			window.location.href = 'list.html';
		}
	</script>
{% endblock %}

templates/goods_category_list.html
{% extends 'base_main.html' %}

{% block content %}
    <section class="rt_wrap content mCustomScrollbar">
        <div class="rt_content">
            <div class="page_title">
                <h2 class="fl">商品列表</h2>
                <a href="goods_category_detail.html" class="fr top_rt_btn add_icon">添加商品</a>
            </div>
            <table class="table">
                <tr>
                    <th>缩略图</th>
                    <th>类型</th>
                    <th>操作</th>
                </tr>
                {% for category in categorys %}
                    <tr>
                        <td class="center"><img src="/media/{{ category.category_front_image }}" width="50" height="50" alt="" /></td>
                        <td class="center">
                            {% for type in types %}
                                {% ifequal type.0 category.category_type %}
                                    {{ type.1 }}
                                {% endifequal %}
                            {% endfor %}
                        </td>
                        <td class="center">
                            <a href="{% url 'goods:goods_category_detail' category.id %}" title="编辑" class="link_icon">&#101;</a>
                        </td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </section>
{% endblock %}

templates/goods_desc.html
{% extends 'base_main.html' %}

{% block js %}
    {{ block.super }}
    <script type="text/javascript" src="/static/kindeditor/kindeditor-all.js"></script>
    <script type="text/javascript" src="/static/kindeditor/lang/zh-CN.js"></script>
    <script type="text/javascript">
        KindEditor.ready(function(K) {
                window.editor = K.create('#editor_id',{
                    uploadJson:'/util/upload/kindeditor'
                });
        });
    </script>
{% endblock %}

{% block content %}
<section class="rt_wrap">

    <div class="rt_content">
        <div class="page_title">
            <h2 class="fl">商品详情</h2>
            <a class="fr top_rt_btn" href="/goods/goods_list/">返回商品列表</a>
        </div>
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <section>
                <ul class="ulColumn2">
                    <li>
                        <span class="item_name" style="width:120px;">产品详情：</span>
                        <label style="display:inline-block;padding:15px;background:#f8f8f8;">
                            <textarea id="editor_id" name="content" style="width:700px;">
                                {{ goods.goods_desc }}
                            </textarea>
                        </label>
                    </li>
                    <li>
                        <span class="item_name" style="width:120px;"></span>
                        <input type="submit" class="link_btn"/>
                    </li>
                </ul>
            </section>
        </form>
    </div>
</section>

{% endblock %}

templates/goods_list.html
{% extends 'base_main.html' %}

{% block content %}
<section class="rt_wrap content mCustomScrollbar">
    <div class="rt_content">
        <div class="page_title">
            <h2 class="fl">商品列表</h2>
            <a href="{% url 'goods:goods_add' %}" class="fr top_rt_btn add_icon">添加商品</a>
        </div>
        <table class="table">
            <tr>
                <th>缩略图</th>
                <th>产品名称</th>
                <th>商品类型</th>
                <th>货号</th>
                <th>市场单价</th>
                <th>本店单价</th>
                <th>库存</th>
                <th>详情</th>
                <th>操作</th>
            </tr>
            {% for good in goods %}
                <tr>
                    <td class="center"><img src="/media/{{ good.goods_front_image }}" width="50" height="50" alt="" /></td>
                    <td class="center">{{ good.name }}</td>
                    <td class="center">
                        {% for type in types %}
                            {% ifequal type.0 good.category_id %}
                                {{ type.1 }}
                            {% endifequal %}
                        {% endfor %}
                    </td>
                    <td class="center">{{ good.goods_sn }}</td>
                    <td class="center"><strong class="rmb_icon">{{ good.market_price }}</strong></td>
                    <td class="center"><strong class="rmb_icon">{{ good.shop_price }}</strong></td>
                    <td class="center">{{ good.goods_nums }}</td>
                    <td class="center">
                        <a href="{% url 'goods:goods_desc' good.id %}">{{ good.name }}的描述</a>
                    </td>
                    <td class="center">
                        <a href="{% url 'goods:goods_edit' good.id %}" title="编辑" class="link_icon">&#101;</a>
                        <a onclick="goods_del({{ good.id }});" title="删除" class="link_icon">&#100;</a>
                    </td>
                </tr>
            {% endfor %}
            {% csrf_token %}
            <script>
                function goods_del(id){
                    var csrf = $('input[name="csrfmiddlewaretoken"]').val()
                    $.ajax({
                        url:'/goods/goods_del/' + id + '/',
                        dataType:'json',
                        type:'POST',
                        headers: {'X-CSRFToken': csrf},
                        success:function(data){
                            if(data.code == '200'){
                                location.reload()
                            }
                        },
                        error:function(data){
                            alert('删除失败')
                        }
                    })
                }
            </script>
        </table>
        <aside class="paging">
            <a>当前{{ goods.number }}页</a>
            <a href="{% url 'goods:goods_list' %}?page=1">第一页</a>
            {% for i in goods.paginator.page_range %}
                <a href="{% url 'goods:goods_list' %}?page={{ i }}">{{ i }}</a>
            {% endfor %}
            <a href="{% url 'goods:goods_list' %}?page={{ goods.paginator.num_pages }}">最后一页</a>
        </aside>
    </div>
</section>

{% endblock %}

templates/index.html
{% extends 'base_main.html' %}

{% block title %}
    后台管理系统
{% endblock %}

{% block content %}
    <section class="rt_wrap content mCustomScrollbar">
        <div class="rt_content">
            <h1 style="color:red;font-size:20px;font-weight:bold;text-align:center;">
                生鲜商城管理后台
            </h1>
            <br>
            <p>商城管理采用Django2.0.7 + Python3.7.0开发，存储数据库为关系型数据库Mysql</p>
            <br>
            <p>商城后台集中功能为：商品分类、商品图片、商品库存、用户管理、收货地址管理、留言管理、订单管理等模块</p>


        </div>
    </section>
{% endblock %}

templates/place_order.html
{% extends 'base_main.html' %}

{% block title %}
    天天生鲜提交订单
{% endblock %}

{% block content %}

	<h3 class="common_title">确认收货地址</h3>

	<div class="common_list_con clearfix">
		<dl>
            <dt>寄送到：</dt>
            {% for address in addresses %}
                <dd><input type="radio" id="radio_{{ address.id }}" value="{{ address.id }}"  name="common_list">
                    {{ address.address }}
                    （{{ address.signer_name }} 收） {{ address.signer_mobile }}
                </dd>
            {% endfor %}
        </dl>
		<a href="{% url 'order:user_order_site' %}" class="edit_site">编辑收货地址</a>

	</div>

	<h3 class="common_title">支付方式</h3>
	<div class="common_list_con clearfix">
		<div class="pay_style_con clearfix">
			<input type="radio" name="pay_style" checked>
			<label class="cash">货到付款</label>
			<input type="radio" name="pay_style">
			<label class="weixin">微信支付</label>
			<input type="radio" name="pay_style">
			<label class="zhifubao"></label>
			<input type="radio" name="pay_style">
			<label class="bank">银行卡支付</label>
		</div>
	</div>

	<h3 class="common_title">商品列表</h3>

	<div class="common_list_con clearfix">
		<ul class="goods_list_th clearfix">
			<li class="col01">商品名称</li>
			<li class="col02">商品单位</li>
			<li class="col03">商品价格</li>
			<li class="col04">数量</li>
			<li class="col05">小计</li>
		</ul>
        {% for cart in carts %}
            <ul class="goods_list_td clearfix">
                <li class="col01">{{ forloop.counter }}</li>
                <li class="col02"><img src="/media/{{ cart.goods.goods_front_image }}"></li>
                <li class="col03">{{ cart.goods.name }}</li>
                <li class="col04">500g</li>
                <li class="col05">{{ cart.goods.shop_price }}元</li>
                <li class="col06">{{ cart.nums }}</li>
                <li class="col07">{{ cart.total_price }}元</li>
            </ul>
		{% endfor %}
	</div>

	<h3 class="common_title">总金额结算</h3>

	<div class="common_list_con clearfix">
		<div class="settle_con">
			<div class="total_goods_count">共<em>2</em>件商品，总金额<b>42.60元</b></div>
			<div class="transit">运费：<b>10元</b></div>
			<div class="total_pay">实付款：<b>52.60元</b></div>
		</div>
	</div>

	<div class="order_submit clearfix">
		<a href="javascript:;" id="order_btn">提交订单</a>
	</div>

{% endblock %}

{% block endjs %}
    <div class="popup_con">
		<div class="popup">
			<p>订单提交成功！</p>
		</div>

		<div class="mask"></div>
	</div>
    <script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
    {% csrf_token %}
	<script type="text/javascript">
		$('#order_btn').click(function() {

		    <!--验证用户是否选择了收货地址-->
		    var radio_length = $('input[name="common_list"]')
            for(var i = 0;i<radio_length.length;i++){
                if(radio_length[i].checked==true){
                    var value = radio_length[i].value;
                    break;
                }
            }
            if(value){
                localStorage.setItem('order_finish',2);

                $('.popup_con').fadeIn('fast', function() {

                    setTimeout(function(){
                        $('.popup_con').fadeOut('fast',function(){
                            window.location.href = '/';
                        });
                    },3000)

                });
                var csrf = $('input[name="csrfmiddlewaretoken"]').val()
                $.ajax({
                    url:'/order/order/',
                    type:'POST',
                    data:{'address_id': value},
                    dataType:'json',
                    headers:{'X-CSRFToken': csrf},
                    success:function(data){
                        console.log(data)
                    },
                    error: function(data){
                        alert('创建订单失败')
                    }
                });
            }else{
                alert('请选择收货人地址信息')
            }
		});
	</script>
{% endblock %}

templates/user_center_order.html
{% extends  'base_main.html' %}

{% block ticle %}
    天天生鲜-商品详情
{% endblock %}

{% block content %}


	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'user:user_center_order' %}">· 个人信息</a></li>
				<li><a href="{% url 'order:user_order' %}" class="active">· 全部订单</a></li>
				<li><a href="{% url 'order:user_order_site' %}">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
            {% csrf_token %}
            {% for o_info in order_info %}
				<h3 class="common_title2">全部订单</h3>
				<ul class="order_list_th w978 clearfix">
					<li class="col01">{{ o_info.add_time|date:'Y-m-d h:m:s' }}</li>
					<li class="col02" style="width:400px;">订单号：{{ o_info.order_sn }}</li>
					<li class="col02 stress">
                        {% for status in order_status %}
                            {% if status.0 == o_info.pay_status %}
                                {{ status.1 }}
                            {% endif %}
                        {% endfor %}
                    </li>
				</ul>

				<table class="order_list_table w980">
					<tbody>
						<tr>
							<td width="55%">

                                {% for order_goods in o_info.goods.all %}
                                    <ul class="order_goods_list clearfix">
                                        <li class="col01"><img src="/media/{{ order_goods.goods.goods_front_image }}"></li>
                                        <li class="col02">{{ order_goods.goods.name }}<em>{{ order_goods.goods.shop_price }}元/500g</em></li>
                                        <li class="col03">{{ order_goods.goods_nums }}</li>
                                        <li class="col04">{{ order_goods.goods.shop_price }}元</li>
                                    </ul>
                                {% endfor %}
							</td>
							<td width="15%">{{ o_info.order_mount }}元</td>
							<td width="15%">
                                {% for status in order_status %}
                                    {% if status.0 == o_info.pay_status %}
                                        {{ status.1 }}
                                    {% endif %}
                                {% endfor %}
                            </td>
							<td width="15%">
                                <a href="#" class="oper_btn">
                                    {% if o_info.pay_status == 'PAYING' %}
                                        <a href="#">去付款</a>
                                    {% endif %}
                                    {% if o_info.pay_status == 'TRADE_SUCCESS' %}
                                        成功
                                    {% endif %}
                                </a>
                            </td>
						</tr>
					</tbody>
				</table>
            {% endfor %}


				<div class="pagenation">
                    {% if page.has_previous %}
					    <a href="{% url 'order:user_order' %}?page={{ page.previous_page_number }}"><上一页</a>
                    {% endif %}
					<a href="#" class="active">1</a>
                    {% for i in page.paginator.page_range %}
					    <a href="{% url 'order:user_order' %}?page={{ i }}">{{ i }}</a>
                    {% endfor %}
                    {% if page.has_next %}
					    <a href="{% url 'order:user_order' %}?page={{ page.next_page_number }}">下一页></a>
                    {% endif %}
				</div>
		</div>
	</div>

{% endblock %}